### ISSUE TITLE
Implement better admin UI for modifying unit/resource opening hours

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/respa#25]

**Comment by juyrjola** [comment]
Some documentation on how the opening hours algorithm and data model is supposed to work:

https://gist.github.com/tituomin/88352932c9c83fa0fd7f

**Comment by akx** [comment]
@tituomin, @juyrjola : Could someone write updated docs for the opening hours algorithm and data model? I understood the above gist is out of date.

**Comment by jussiarpalahti** [comment]
@akx, this spec was written originally for https://github.com/libraries-fi/Library-Directory-Admin back in the day.

It explains the JSON document model stored in ElasticSearch. Respa has the same data (sort of) modeled as in Django ORM, plus some modifications/simplifications.

Since I made the newest implementation it might behoove me to write its docs.

Question is, should I document the ORM side, or merely the conceptual model, or how to make use of the data in db? Anything specific you'd like to docs to clarify?

**Comment by akx** [comment]
@jussiarpalahti: I think I kinda got the general idea when working on this and #40, so I'm all good :) 

Doesn't mean that docs would go amiss though...
