### ISSUE TITLE
Flag staff reservations

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/respa#466]
Staff make reservations for the middle of the day to block out certain times from being booked by citizens. These reservations artificially inflate our statistics. They should be flagged as staff reservations so they are separate from citizen reservations in our statistics.

**Comment by jussih** [comment]
There seems to be a concept of staff reservation already in Varaamo.

![screenshot from 2019-02-25 16-52-23](https://user-images.githubusercontent.com/668554/53346691-31473e00-3920-11e9-95da-e73b5169f142.png)

Checking this bypasses some otherwise mandatory reservation fields. The "staff event" state does not seem to be saved to backend - the UI has some logic to deduce whether a Reservation is a staffEvent or not: https://github.com/City-of-Helsinki/varaamo/blob/develop/app/utils/reservationUtils.js#L30

We could create a flag in the data model for Reservation to save the staff reservation information. The checkbox in the UI could stay as is and would be then saved in the Reservation itself for statistics purposes.

**Comment by petterill** [comment]
@jussih yes, good call! Let's make it so that the staff event state is saved in the backend.

**Comment by petterill** [comment]
We should also be able to separate staff reservations in the reports/stats, especially in the excel report used by Varaamo people https://api.hel.fi/respa/v1/reservation/?format=xlsx
